### PR TITLE
Remove SSL cert file generators and var def in maestro config

### PR DESCRIPTION
**Pull request by mray190**
Now that maestro.config lives within snap-pelion-edge, port wwrelay-utils/edge-utils PRs into the snap repo

### CODE REVIEW

**Comment by mray190** [comment]
Porting over: https://github.com/armPelionEdge/edge-utils/pull/31

**Comment by psppalash** [comment]
@mray190 I can test this PR on hardware and then we can merge this.

**Review by johnmichaelwelsh — APPROVED** [review]
LGTM

**Comment by mray190** [comment]
Wait for https://github.com/armPelionEdge/snap-pelion-edge/pull/272

**Comment by psppalash** [comment]
Tested on hardware. All services are up and running. Gateway connects to portal and I am able to use relay-term and see logs in the portal.

**Pull request merged**
