### PR TITLE
Point README content to published documentation

### PR DESCRIPTION
**Pull request by AnotherButler**
Point README to published, rendered documentation to prevent duplication and syncing errors.

### CODE REVIEW

**Comment by costanic** [comment]
How do we submit changes going forward?

**Comment by AnotherButler** [comment]
> How do we submit changes going forward?

Going forward, please put PRs against https://github.com/ARMmbed/pelion-dm-edge-docs/blob/master/docs/quick-start/snapcraft.md

**Comment by costanic** [comment]
> > How do we submit changes going forward?
> 
> Going forward, please put PRs against https://github.com/ARMmbed/pelion-dm-edge-docs/blob/master/docs/quick-start/snapcraft.md

Thanks.

It looks like that repo and the snapcraft quickstart is behind this version.  Can we make sure the new doc is up-to-date with this README before we replace it?

**Comment by AnotherButler** [comment]
They are now in alignment: https://github.com/ARMmbed/pelion-dm-edge-docs/pull/85. Please merge this when possible to prevent further version control issues.

**Review by costanic — APPROVED** [review]

**Pull request merged**
