### PR TITLE
update maestro-shell

### PR DESCRIPTION
**Pull request by psppalash**
Include maestro-shell wifi support changes.

### CODE REVIEW

**Comment by costanic** [comment]
Requires: https://github.com/armPelionEdge/maestro-shell/pull/16

**Comment by mray190** [comment]
@psppalash I merged the original commit into master of maestro-shell.
This PR will need to be updated with the new hash and then we are good to go!

**Review by mray190 — CHANGES_REQUESTED** [review]
See comment above

**Comment by psppalash** [comment]
> @psppalash I merged the original commit into master of maestro-shell.
> This PR will need to be updated with the new hash and then we are good to go!

I think the commit was merged into dev of maestro-shell. We still need to move the commits to master.

**Comment by psppalash** [comment]
Updated the SHA. Please squash and merge.

**Review by mray190 — APPROVED** [review]

**Pull request merged**
