### PR TITLE
Enable snapd managed updates

### PR DESCRIPTION
**Pull request by ryannowarm**
We launch snap install/refresh via Pelion update(FOTA).  So disable
snapd automatic updates using the snapd managed updates feature.

### CODE REVIEW

**Comment by ryannowarm** [comment]
@tonyespy, FYI

**Comment by costanic** [comment]
If the snap is installed with this plug, and the user subsequently sets the snap refresh.timer to managed via command line at the factory, how would updates be scheduled from then on?  would the user have to log into each gateway and manually initiate an update?  or will there be a follow-on feature which allows the user to remote initiate an update?  I assume this would be part of Pelion FOTA process?

**Comment by ryannowarm** [comment]
@costanic, correct.

**Comment by mray190** [comment]
Waiting to merge after v1.16.2 release

**Comment by kylestein-arm** [comment]
rebased on current dev

**Pull request merged**
