### PR TITLE
Bump Maestro-shell version

### PR DESCRIPTION
**Pull request by moonchen**
Include changes for configuring an LTE interface.

### CODE REVIEW

**Comment by moonchen** [comment]
> the SHA for maestro-shell must be changed in 2 places. See line 480.

Made the change and force pushed.

**Comment by costanic** [comment]
Waiting for: https://github.com/armPelionEdge/maestro-shell/pull/13

**Comment by costanic** [comment]
https://github.com/armPelionEdge/maestro-shell/pull/13 was merged, but it had to be rebased so the SHA changed.  This PR now needs to be updated with the new maestro-shell SHA.

**Comment by moonchen** [comment]
> [armPelionEdge/maestro-shell#13](https://github.com/armPelionEdge/maestro-shell/pull/13) was merged, but it had to be rebased so the SHA changed. This PR now needs to be updated with the new maestro-shell SHA.

Done

**Pull request merged**
