### PR TITLE
update maestro-shell 

### PR DESCRIPTION
**Pull request by psppalash**
Update maestro-shell to include wifi support

### CODE REVIEW

**Comment by psppalash** [comment]
@mray190 The previous PR did not update maestro-shell to the correct SHA. This PR will update it to latest dev branch of maestro-shell.

**Review by mray190 — APPROVED** [review]

**Comment by mray190** [comment]
@psppalash need a fix to pass CI

**Comment by psppalash** [comment]
> @psppalash need a fix to pass CI

@mray190 Is the build failing?

**Comment by ryannowarm** [comment]
@psppalash, take a look... seems CI failed.  Reach out if you need help figuring it out.

**Comment by psppalash** [comment]
Thanks @mray190 @ryannowarm Looks like the build failed. The CI link was not working for me earlier so I didn't know what was wrong.
Will fix the build issue.

**Comment by psppalash** [comment]
This PR will fix the build issue https://github.com/armPelionEdge/maestro-shell/pull/18

**Comment by psppalash** [comment]
@mray190 I am not sure why the third check is stuck at "pending". An idea what is failing?

**Comment by psppalash** [comment]
@mray190 This PR is ready to be merged now.

**Pull request merged**
